[server]
host = "192.168.10.19"
port = 5555


[events]
publish = "tcp://192.168.10.10:6442"
subscribe = "tcp://192.168.10.10:6443"

[node]
session-timeout = "300"
override-max-sessions = false
detect-drivers = false
drain-after-session-count = 0
max-sessions = 1

[relay]
# Default Appium server endpoint
url = "http://localhost:4723/wd/hub"
status-endpoint = "/status"
# Stereotypes supported by the service
configs = [
"1", "{\"browserName\": \"OnePlus\", \"platformName\": \"android\", \"appium:platformVersion\": \"9\", \"appium:udid\": \"192.168.10.18:5555\", \"appium:port\":\"6300\"}"]